InClassWork/InClassWork/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace InClassWork.Models
{
    public class Car
    {
        //Simple Car Properties
        [Key]
        public int Car_ID { get; set; } //PK for car

        [Required]
        [RegularExpression("..+", ErrorMessage = "Must be at least 2 characters long")]
        public string Model { get; set; } //Car Model

        [Range(10, 5000)]
        public double MaxSpeed { get; set; } //Max Speed

        public string ImageName { get; set; } //Image

        public int Manufacturer_ID { get; set; }

        public virtual Manufactorer Manufactorer { get ;set;}
    }
}

InClassWork/InClassWork/Controllers/CarsController.cs
using InClassWork.Models;           //Use our CarFactory Class
using InClassWork.ViewModels.Home;  // Use our viewmodel
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InClassWork.Controllers
{
    public class CarsController : Controller
    {
        // GET: Cars
        public ActionResult CarsList() //this acts as the URL
        {
            //factory -> a new instance of the CarFactory Model
            var factory = new CarFactory();
            //view model -> the viewmodel filled with the cars list
            var viewModel = new CarListViewModel(factory.Cars);

            return View(viewModel);
        }

        public ActionResult ListOfCars(string searchCriteria)
        {
            var factory = new CarFactory();
            IQueryable<Car> cars = factory.Cars.OrderBy(p => p.Model);

            if (searchCriteria != null)
            {
                cars = cars.Where(p => p.Model.Contains(searchCriteria));
            }

            var carlist = cars.Take(10).ToList();
            //var cars = new CarFactory().Cars.ToList();
            return View(carlist);
        }

        public ActionResult Details(int id)
        {
            var factory = new CarFactory();
            Car found = factory.Cars.Where(p => p.Car_ID == id).FirstOrDefault();

            return View(found);
        }
    }

}

InClassWork/InClassWork/Views/Cars/CarsList.cshtml
@model InClassWork.ViewModels.Home.CarListViewModel

@{
    ViewBag.Title = "CarsList";
}

<h2>CarsList</h2>

@Html.ListBox("carsList", Model.CarsList)

<h2> Fastest Car </h2>
<dl>
    <dt>ID</dt>
    <dd>@Model.FastestCar.Car_ID</dd>

    <dt>Model</dt>
    <dd>@Model.FastestCar.Model</dd>

    <dt>Max Speed</dt>
    <dd>@Model.FastestCar.MaxSpeed</dd>
</dl>

InClassWork/InClassWork/Views/Cars/Details.cshtml
@model InClassWork.Models.Car

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxSpeed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxSpeed)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Car_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

InClassWork/InClassWork/Views/Cars/ListOfCars.cshtml
@model List<InClassWork.Models.Car>

@{
    ViewBag.Title = "ListOfCars";
}

<h2>ListOfCars</h2>

<div class="row">
    <div class="col-md-4">
        <h2>This Week's Deals</h2>
        <p>
            Welcome to our showroom. Treat yourself to a safe new vehicle.
        </p>
    </div>
    <div class="col-md-8">
        @*SEARCH FUNCTIONALITY*@
        @using (Html.BeginForm("ListofCars", "Cars"))
        {
            @Html.TextBox("searchCriteria")
            <input type ="submit" value ="Find Cars" />
        }
        <h2>THis weeks deals:</h2>
        <table class="table-striped table-bordered table-responsive">
            @*Loop through each car sent as a list and display basic information*@
            @foreach (var car in Model)
            {
                <tr>
                    <td>@car.Model</td>
                    <td>@car.MaxSpeed</td>
                    <td>@Html.ActionLink("Details", "Details", new { id = car.Car_ID })</td>
                </tr>
                }
        </table> 
    </div>
</div>